name: Build Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'  # 设置Go版本

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for linux-mipsle
        env:
          GOARCH: mipsle
          GOOS: linux
        run: |
          go build -o your_program_name main.go
          
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-mipsle-binary
          path: your_program_name
